project:
  type: website


website:
  navbar:
    # background: primary
    search: true
    left:
      - index.qmd
      - syllabus.qmd
      - lectures.qmd
      - assignments.qmd

format:
  html:
    theme: sandstone
    toc: true

execute:
  freeze: auto

lang: es

bibliography: references.bib