project:
  type: website

website:
  title: "Herramientas Estadísticas en R"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Programa"
        href: syllabus.qmd
      - text: "Clases"
        href: lectures/lecture1.qmd
      - text: "Tareas"
        href: assignments/assignment1/instructions.qmd
      - text: "Recursos"
        href: resources/textbooks.qmd
