---
title: "Temario"
subtitle: "Herramientas estadísticas en R"
author: "Esteban Degetau"
date: 2025-03-15
date-format: long
format:
  html:
    theme: sandstone
    toc: true
  pdf: default
---

## Objetivo

R es un lenguaje de computación diseñado específicamente para análisis estadístico y gráfico [@crawley2012]. El objetivo de este curso es brindar las herramientas estadísticas para resolver problemas de datos cotidianos en organizaciones grandes como el IMSS. Al final del curso podrás:

1.  Resolver una variedad de preguntas empíricas usando R.
2.  Implementar flujos de datos automáticos desde la fuente de datos hasta medios de comunicación diversos (tablas, figuras, reportes, presentaciones, páginas web, etc.).
3.  Usar Quarto para escribir reportes reproducibles y GitHub para versión de control.

**Prerequisitos**: Este curso asume que tienes conocimientos básicos de estadística y programación. No asumo que tengas experiencia previa con R.

## Contenido

1.  R y el Tidyverse
    -   El lenguaje estadístico R
    -   Paquetes del Tidyverse
    -   Manupulación de datos con `dplyr`
    -   Visualización de datos con `ggplot2`
    -   Programación funcional con `purrr`
    -   Reportes reproducibles con Quarto

    Referencias: @crawley2012; @wickham2017r; @wickham2010; @wickham2019.

1.  Inferencia estadística
    -   Propiedades asintóticas de los estimadores
    -   Pruebas de hipótesis
    -   Bootstrap y métodos de remuestreo
    -   Simulaciones

    Referencias: @aguilaresteva; @schmelzer; @çetinkaya-rundel2024.

1.  Regresión lineal
    -   Mínimos cuadrados ordinarios
    -   Inferencia estadística
    -   Interpretación de coeficientes
    -   Sesgo por variables omitidas
    -   Efectos fijos con `fixest`

    Referencias: @aguilaresteva; @schmelzer; @cunningham2021.

1.  Pronóstico de series de tiempo
    -   Suavización exponencial
    -   ARIMA
    -   Pronóstico automatico con `fable`

    Referencias: @hyndman2008; @hyndman2021.

1.  Aprendizaje de máquina
    -   Supervisado: OLS y clasificación
    -   No supervisado: Componentes principales y clasificación
    -   Elevar la práctica del modelaje con `Tidymodels`

    Referencias: @athey2019; @james2021; @silge.

## Fechas y programa

Las clases son de manera presencial en la Sala de Juntas de la CPE los Miércoles de 12 a 14 h. Tomaremos cinco clases en total del 19 de marzo al 16 de abril.

## Evaluación

### Tareas: 50%

A lo largo del curso, asignaré una tarea por cada tema. Las tareas se entregarán en la fecha indicada en clase. Pueden discutir las tareas con sus compañeros, pero cada estudiante debe entregar su propio trabajo. 

La entrega de la tarea consta de un documento PDF con los análisis requeridos y el código de Quarto que genera el documento. Parte importante de la calificación de las tareas es que el código de Quarto corra sin errores en mi computadora.

Las tareas serán difíciles y requerirán tiempo para completarlas. No dejen las tareas para el último día.

### Proyecto final: 50%

El proyecto final debe cumplir con las siguientes características:

1. Analizar datos del IMSS.
2. Comunicar el análisis en un reporte reproducible de Quarto.
3. Explorar alguna pregunta importante en tu trabajo.

Los requisitos del proyecto final son intencionalmente vagos para permitir la creatividad y la exploración de temas que te interesen o que estén relacionados con tu trabajo.

El objetivo principal del proyecto final es que aprendas cómo puedes usar R y Quarto para resolver problemas cotidianos en tu trabajo.

Algunos ejemplos de proyectos finales son:

- La automatización de (alguna porción de) algún reporte o presentación mensual que ya tengas.
- Un ejercicio de predicción de series de tiempo (por ejemplo, fijación de metas).
- Un análisis de regresión de alguna variable de interés.
- Un ejercicio de clasificación supervisada o no supervisada.

Cualquier otro proyecto que cumpla con los requisitos es más que bienvenido. Si tienes una idea vaga de qué podrías hacer, podemos discutirlo en clase.

:::{.callout-important}
## No trabajes en Excel

Puesto que el objetivo del curso es aprender a programar en R y establecer flujos de datos automatizados,  no se aceptarán tareas o proyectos que usen Excel para pasos intermedios.
:::

## Recursos adicionales

Además de las referencias en este documento, también puedes encontrar ligas de interes en la página de [recursos](resources.qmd).
