---
title: "Instalación del software"
subtitle: "Tarea 0"
date: "2025-03-14"
format:
    pdf: 
        date-format: long
number-sections: true
---

Antes de comenzar el curso, es necesario que instales el software que utilizaremos. Esta tarea no tiene entregable. Solo es necesario que hayas seguido cada uno de los pasos siguientes antes de la primera clase, el miércoles 19 de marzo.

## Instala R

Para instalar R en Windows, sigue las instrucciones en la liga: <https://cran.r-project.org/bin/windows/base/>.

Para instalar R en macOS, sigue las instrucciones en la liga: <https://cran.r-project.org/bin/macosx/>.

## Instala RStudio

RStudio es un entorno de desarrollo integrado (IDE) para R. Puedes descargarlo de la liga: <https://www.rstudio.com/products/rstudio/download/>. Ojo: si ya instalaste R para este punto, solo necesitas instalar RStudio.

Este paso en realidad es opcional. Si prefieres trabajar en VSCode o en otro IDE, adelante.

## Instala Quarto

Quarto es un software que permite crear *reportes computacionales* con R para exportar en una variedad de formatos. Todas las tareas se entregarán en documentos creados por Quarto. Para instalar Quarto, sigue las instrucciones en la liga: <https://quarto.org/docs/getting-started/installation.html>.
